<a href="https://colab.research.google.com/github/jittakorn-ch/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Function

Function มีส่วนสำคัญทั้งหมด 4 ส่วน

1. บอก python ว่าเราจะเขียนฟังค์ชั่น ชื่ออะไร def function_name(): (ขาดไม่ได้)
2. กำหนดตัวแปรที่จะเป็น input **input* (ขาดไม่ได้)
3. ส่วนประมวลผล do_something with *input* to get Output (ขาดไม่ได้)
4. ส่วน putput return *Output* (ขาดไม่ได้)

เราใช้ เว้นวรรค(indent) เพื่อกำหนดขอบเขต

In [3]:
def print_name(name,surname,ID):   # มีกี่ตัวแปรก็ได้
  st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
  return st

เรียกใช้ฟังค์ชั่น

In [4]:
print_name('จิตรกร', 'จันทะสี', '623021044-1')

'ชื่อ จิตรกร นามสกุล จันทะสี ID 623021044-1'

In [5]:
def print_name2(name,ID,surname):   # มีกี่ตัวแปรก็ได้
  st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
  print(st)

In [6]:
print_name2('จิตรกร', 'จันทะสี', '623021044-1')

ชื่อ จิตรกร นามสกุล 623021044-1 ID จันทะสี


In [7]:
op2 = print_name2('จิตรกร', 'จันทะสี', '623021044-1')

ชื่อ จิตรกร นามสกุล 623021044-1 ID จันทะสี


In [8]:
print(op2)

None


ฟังค์ชั่นไม่จำเป็นต้องมี input

In [9]:
def Pi():
  return 3.14159265359

In [10]:
#คำพื้นที่วงกลมที่มีขนาดเส้นผ่านศุนย์กลางเท่ากับ 3
Pi()*(1.5**2)

7.0685834705775

In [11]:
def print_my_name():
  print('จิตรกร จันทะสี ID 623021044-1')

In [12]:
print_my_name()

จิตรกร จันทะสี ID 623021044-1


###input ของ function ใน python มีสองแบบ input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส่ (มีาค่า default) เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [13]:
def print_2lines_default(name, surname, ID, grade='F'):
  st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
  print(st)
  st2=f'เกรดวิชา Multivariat >>> {grade}'
  print(st2)

In [14]:
print_2lines_default('จิตรกร','จันทะสี','623021044-1')

ชื่อ จิตรกร นามสกุล จันทะสี รหัส 623021044-1
เกรดวิชา Multivariat >>> F


In [15]:
print_2lines_default('จิตรกร','จันทะสี','623021044-1','A')

ชื่อ จิตรกร นามสกุล จันทะสี รหัส 623021044-1
เกรดวิชา Multivariat >>> A


เราสามารถเรียกฟังค์โดยใช้ชื่อตัวแปรของฟังค์ชั่นช่วยได้

In [16]:
print_name2(name='จิตรกร', surname='จันทะสี', ID='623021044-1')

ชื่อ จิตรกร นามสกุล จันทะสี ID 623021044-1


####HW3 ให้เขียน function คำนวณจำนวนวินาที เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [17]:
def print_time(time):
         time_sp = time.split('-') 
         answer = int(time_sp[0])*60*60 + int(time_sp[1])*60 + int(time_sp[2])
         print(f'เวลา {time} คำนวณเป็นจำนวนวินาทีได้เท่ากับ {answer} วินาที')

In [18]:
print_time('14-15-31')

เวลา 14-15-31 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 51331 วินาที


In [19]:
print_time('13-00-01')

เวลา 13-00-01 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 46801 วินาที


In [20]:
print_time('05-49-44')

เวลา 05-49-44 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 20984 วินาที


In [21]:
print_time('00-00-16')

เวลา 00-00-16 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 16 วินาที


Numpy -> packge สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num + py -> Number-Numerical + python

การใช้ package

1.```imput```





In [26]:
import numpy

สร้าง array (numpy array)

In [30]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [31]:
mat_ex1[1,1]  #[แถว,หลัก] เริ่มจาก 0,1,2,..

0.1

ถ้าไม่มี numpy array

In [32]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [35]:
list_ex1[1][1]

0.1

Matrix Operation

data 2 แบบ -> matrix (2D array),scalar(ตัวเลขค่าคงที่)

In [36]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[9.1,1.5,1.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[2.  3.7 5.9]
 [9.1 1.5 1.3]]


####บวกกับลบ matrix เอาตำแหน่งเดียวกันมาบวกหรือลบกัน

(หน้าตาของ matrix ต้องเหมือนกัน)

In [39]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)

[[ 7.2  6.7 10.4]
 [18.2  1.6  1.6]]
[[ 3.2 -0.7 -1.4]
 [ 0.  -1.4 -1. ]]


####การตรวจสอบขนาดของ matrix

In [40]:
mat_ex3.shape

(2, 3)

In [41]:
mat_ex3.shape[0]

2

####คูณ matrix

In [44]:
print(mat_ex1)
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[2.  3.7 5.9]
 [9.1 1.5 1.3]]


In [43]:
mat_ex1 * mat_ex2

array([[10.4 , 11.1 , 26.55],
       [82.81,  0.15,  0.39]])

In [46]:
numpy.dot(mat_ex1,mat_ex2)

NameError: ignored

#### การคูณ matirx (แถวคูณหลัก)
(หลักของ Matrix ตัวข้างหน้า ต้องเท่ากับแถวของ Matrix ตัวข้างหลัง)
dot product (AAA,x),(x,ZZZ) = (AAA,ZZZ)

In [48]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[2.  3.7 5.9]
 [9.1 1.5 1.3]]
(2, 3)


####Transpose กลับแถวเป็นหลักกลับเป็นแถว

matrix.T

In [50]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2)

array([[48.05, 57.67],
       [20.34, 83.35]])

In [52]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3) =(3,3)

array([[93.21, 32.89, 42.51],
       [ 6.91, 11.25, 17.83],
       [11.73, 17.1 , 26.94]])

HW4 อธิบายการหา Determinant และ Inverse matrix (รูปและคำอธิบาย)